# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/JIANG/Desktop/ICC/109_geofence/vivado/vivado.srcs/sources_1/ip/sqrt_ip/sqrt_ip.xci
# IP: The module: 'sqrt_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JIANG/Desktop/ICC/109_geofence/vivado/vivado.gen/sources_1/ip/sqrt_ip/sqrt_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/JIANG/Desktop/ICC/109_geofence/vivado/vivado.srcs/sources_1/ip/sqrt_ip/sqrt_ip.xci
# IP: The module: 'sqrt_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/JIANG/Desktop/ICC/109_geofence/vivado/vivado.gen/sources_1/ip/sqrt_ip/sqrt_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sqrt_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
